### PR TITLE
Npm CD

### PR DESCRIPTION
**Pull request by 0xorial**
@rhys-vdw  After some tinkering I came up with this git action to upload package to npm. I think I don't have access to set repository secret so you would need to make one called 'NPM_TOKEN'.

### CODE REVIEW

**Comment by rhys-vdw** [comment]
Oh amazing. I've never played with GH CI. So you just add the GitHub bot to npm?

**Comment by rhys-vdw** [comment]
When does the deployment run? Any merge to master?

**Comment by rhys-vdw** [comment]
I've added the npm secret. I'm guessing the publish command will just fail unless the `version` has been changed? I am not sure how to generate a GitHub secret though...

**Comment by 0xorial** [comment]
Yeah, I configured it to only bump 'prerelease' version and run on every push to master (except commits starting with [skip ci] - I wonder if that would trigger infinite execution xD).
It was my first time trying github actions actually. Github secret seems to be there automatically: https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow

The general idea - on every push it bumps version and commits, then pushes to npm, then pushes the commit.

**Comment by rhys-vdw** [comment]
That makes sense for now. I guess we'll have to change this when we want to actually release 1.0.0 etc?

**Comment by rhys-vdw** [comment]
Also, amazing work.

**Pull request merged**
