### PR TITLE
Broken a big file into smaller files. Added .test suffix for test files.

### PR DESCRIPTION
**Pull request by 0xorial**

### CODE REVIEW

**Comment by rhys-vdw** [comment]
Haha, I hope you automated this process. 😆

All tests appear to be passing so LGTM! Does this not close #192?

**Comment by 0xorial** [comment]
hehe, yeah, you can see that in the intermediate commit.
I guess we indeed can close it.
meanwhile I kinda go hooked on TAP and [looking around](https://github.com/ljharb/tape/issues/582) if we can make it great :)

**Comment by rhys-vdw** [comment]
re https://github.com/ljharb/tape/issues/582#issuecomment-1280031161

I'm on windows and can run the test suite just fine. Although I didn't test it after your refactor (just trusted CI)

**Comment by rhys-vdw** [comment]
> meanwhile I kinda go hooked on TAP

It's awesome isn't it? I love how simple it is.

**Comment by 0xorial** [comment]
> I'm on windows and can run the test suite just fine. Although I didn't test it after your refactor (just trusted CI)

tape itself runs on windows, I just have problem with running the tests of the tape itself...

> It's awesome isn't it? I love how simple it is.

There is a certain OCD joy in having a spec dictating how test runner should interact with the host (test runners/frameworks seem practically identical features reporting-wise, even if I take .net frameworks into account, so it would be so much cooler if IDEs could just support TAP-compatible runner (although this would probably require to include CLI parameters specs in the TAP)  :)

**Pull request merged**
