### PR TITLE
Fix 219: stringify index keyType in debug build

### LINKED ISSUE #219: Debug build does not quote the type of Record keys
This seems to be a regression in 4.1.0 when building in debug mode. It works in 4.0.0 but not in 4.1.0 or 4.1.1.

Example:
```ts
/** @see {isRecordGuard} ts-auto-guard:type-guard */
export interface RecordGuard {
  optional?: Record<string, string>;
  required: Record<string, string>;
}
```

Generated guard:
```ts
import { RecordGuard } from "./RecordGuard";

function evaluate(
    isCorrect: boolean,
    varName: string,
    expected: string,
    actual: any
): boolean {
    if (!isCorrect) {
        console.error(
            `${varName} type mismatch, expected: ${expected}, found:`,
            actual
        )
    }
    return isCorrect
}

export function isRecordGuard(obj: unknown, argumentName: string = "recordGuard"): obj is RecordGuard {
    const typedObj = obj as RecordGuard
    return (
        (typedObj !== null &&
            typeof typedObj === "object" ||
            typeof typedObj === "function") &&
        evaluate((typeof typedObj["optional"] === "undefined" ||
            (typedObj["optional"] !== null &&
                typeof typedObj["optional"] === "object" ||
                typeof typedObj["optional"] === "function") &&
            Object.entries<any>(typedObj["optional"])
                .every(([key, value]) => (evaluate(typeof value === "string", `${argumentName}["optional"]["${key.toString().replace(/"/g, '\\"')}"]`, "string", value) &&
                    evaluate(typeof key === "string", `${argumentName}["optional"] (key: "${key.toString().replace(/"/g, '\\"')}")`, string, key)))), `${argumentName}["optional"]`, "Record<string, string> | undefined", typedObj["optional"]) &&
        evaluate((typedObj["required"] !== null && //                                                                 Needs quoting ----^----
            typeof typedObj["required"] === "object" ||
            typeof typedObj["required"] === "function") &&
            Object.entries<any>(typedObj["required"])
                .every(([key, value]) => (evaluate(typeof value === "string", `${argumentName}["required"]["${key.toString().replace(/"/g, '\\"')}"]`, "string", value) &&
                    evaluate(typeof key === "string", `${argumentName}["required"] (key: "${key.toString().replace(/"/g, '\\"')}")`, string, key))), `${argumentName}["required"]`, "Record<string, string>", typedObj["required"])
    ) //                                                                                                              Needs quoting ----^----
}
```

### PR DESCRIPTION
**Pull request by Hyddan**
Fixes #219

### CODE REVIEW

**Comment by rhys-vdw** [comment]
Thanks @Hyddan! Would be good to add a test case for this if you're willing. Happy to merge without, just let me know.

**Comment by rhys-vdw** [comment]
Thanks @Hyddan! Looks like prettier failed on your test case. You can fix it with `npx prettier --write .` in the directory if you don't have a prettier plugin for your IDE.

**Comment by Hyddan** [comment]
@rhys-vdw Aah, sorry, should be fixed now!

**Comment by rhys-vdw** [comment]
Thanks @Hyddan! I've invited you to become a collaborator, should you wish. If you do, you're not obliged to contribute, but if you want to add a feature please go through the normal process of opening an issue first and getting a review before you merge.

Just [released version 4.1.2](https://github.com/rhys-vdw/ts-auto-guard/actions/runs/3572502543/jobs/6005464310) so your changes are live.

**Pull request merged**
