### PR TITLE
Dependency Updates

### PR DESCRIPTION
**Pull request by elliot-huffman**
## Changelog
- Match the earliest [currently supported LTS](https://nodejs.org/en/about/previous-releases) version of Node.JS | Node 18 LTS
- Migrate ESLint/Typescript-ESlint to the [new flat config](https://typescript-eslint.io/blog/announcing-typescript-eslint-v7) standard in prep for the ESLint 9 migration (after [typesccript-eslint v8 is released](https://typescript-eslint.io/blog/announcing-typescript-eslint-v8-beta))
- Update TypeScript config to the latest version
- Update Typescript output to match the [latest version of ECMAScript supported by Node 18 LTS](https://node.green/#ES2023). (ES2022)
    - Match language feature configuration to the new language target
- Disable declaration source generation since that goes un-used in dev.
- Remove comments from the transpiled source output since that is not needed in production and the source maps point back to the typescript files.
- Update all dependencies to the latest versions available
- Add compile script for production builds that is production optimized
    - Removes the source maps since the source is not included in the published output
- Remove Prettier JS and JSON checks since those files don't exists or don't need to be checked.

## BREAKING CHANGES
- New minimum Node.JS version required is 18 LTS!
- Declaration **map** files (`d.ts.map`) are no longer generated (the `d.ts` files still are though)

### CODE REVIEW

**Comment by elliot-huffman** [comment]
@rhys-vdw, I honestly don't know how to fix the latest failing test. Everything except that one test passes, and I can't seem to track down where the generated file shows up and what is expected of it to verify the content is expected. Would you be able to assist me with this?

**Comment by elliot-huffman** [comment]
@rhys-vdw 

Got the test fixed. Turns out the new ES2022 target was changing the import/export logic slightly, I updated the hard coded test to match the new output.
Plz take a peek at the total updates and merge if you are happy!

Don't forget to enable [socket](https://socket.dev) to do dependency scanning.

**Comment by rhys-vdw** [comment]
Nice one. In [a recent project](https://github.com/EffortStar/es-changelog/blob/70d17442b484cc29a678198eaec4239fb02c849e/tsconfig.json) I discovered that you can greatly simplify tsconfig by using the `extends` command these days. The one in the project is an absolute mess hahaha. Might be worth doing if you're in the mood for further cleaning.

> Declaration map files (d.ts.map) are no longer generated (the d.ts files still are though)

Do these have any value? I don't recall deliberately enabling their generation.

> Don't forget to enable [socket](https://socket.dev/) to do dependency scanning.

I have enabled it for this repo now, but only after the tests ran. I'm not sure I can trivially re-run it for this PR.

Otherwise looks great, thanks for doing this drudgework of bringing the project up to speed. Feel free to make other improvements as required, but for anything major I'd prefer an issue were opened for discussion first.

I'm happy to merge this one but I'll let you do the honours. I'll get a notification and can run the release script when it's done.

**Comment by elliot-huffman** [comment]
> Nice one. In [a recent project](https://github.com/EffortStar/es-changelog/blob/70d17442b484cc29a678198eaec4239fb02c849e/tsconfig.json) I discovered that you can greatly simplify tsconfig by using the `extends` command these days. The one in the project is an absolute mess hahaha. Might be worth doing if you're in the mood for further cleaning.
> 
> > Declaration map files (d.ts.map) are no longer generated (the d.ts files still are though)
> 
> Do these have any value? I don't recall deliberately enabling their generation.
Only for a certain type of debugging that I don't expect us to do on our side. I am prepping a new PR for deep VS code integration which actually uses the map files but only the `.ts` maps, not the `.d.ts` maps.

I am not aware of anything that you are currently doing that would require them, they 100% aren't useful for end users since you don't ship the `*.ts` files source code with your NPM packages.

> 
> > Don't forget to enable [socket](https://socket.dev/) to do dependency scanning.
> 
> I have enabled it for this repo now, but only after the tests ran. I'm not sure I can trivially re-run it for this PR.
Awesome!
> 
> Otherwise looks great, thanks for doing this drudgework of bringing the project up to speed. Feel free to make other improvements as required, but for anything major I'd prefer an issue were opened for discussion first.
No worries, can do :)
> 
> I'm happy to merge this one but I'll let you do the honours. I'll get a notification and can run the release script when it's done.

I prefer you to do the merges as I don't want to overstep my permissions that you have granted me.

Technically I can bypass merge reviews since you made me a contributor, if this was not intentional, I can show you have to enforce branch protection policies on the project to prevent people like me from taking over the project :-P

**Comment by rhys-vdw** [comment]
> Only for a certain type of debugging that I don't expect us to do on our side. I am prepping a new PR for deep VS code integration which actually uses the map files but only the .ts maps, not the .d.ts maps.

Oh sorry, I understood this to mean that ts-auto-guard was outputting them. Yeah, they have no use in the build process.

> Technically I can bypass merge reviews since you made me a contributor, if this was not intentional, I can show you have to enforce branch protection policies on the project to prevent people like me from taking over the project :-P

Ah that's fine, you don't have the ability to do a release which is the only real security concern IMO.

**Comment by elliot-huffman** [comment]
> > Only for a certain type of debugging that I don't expect us to do on our side. I am prepping a new PR for deep VS code integration which actually uses the map files but only the .ts maps, not the .d.ts maps.
> 
> Oh sorry, I understood this to mean that ts-auto-guard was outputting them. Yeah, they have no use in the build process.
> 
> > Technically I can bypass merge reviews since you made me a contributor, if this was not intentional, I can show you have to enforce branch protection policies on the project to prevent people like me from taking over the project :-P
> 
> Ah that's fine, you don't have the ability to do a release which is the only real security concern IMO.

Check your email on that last one. Sent you a security risk notice.

**Comment by rhys-vdw** [comment]
Hey @elliot-huffman, just running the release now. https://github.com/rhys-vdw/ts-auto-guard/actions/runs/9459986476

Will reply to your email in time, bit busy atm. :-)

**Comment by rhys-vdw** [comment]
Ah looks like I need to make some token updates. Will handle in time!

**Pull request merged**
