### PR TITLE
Truncate nested import statements

### PR DESCRIPTION
**Pull request by chooban**
Of course, as soon as the previous PR was merged I came across an edge case! However, good news is that I also figured out how to add a proper test for it, so it hopefully won't come back, and other edge cases will hopefully be testable.

### CODE REVIEW

**Comment by rhys-vdw** [comment]
Hey @chooban, we actually [don't assume that `process.cwd()` is the root of the project](https://github.com/rhys-vdw/ts-auto-guard/blob/e56198be832ee20f0beea4773fed358574ab8b28/src/cli.ts#L94). The correct behaviour here would be to pass the path of the tsconfig through (if possible). Thoughts?

**Comment by chooban** [comment]
That's interesting! In our project we don't have `tsconfig.json` in the root, we have `tsconfig.base.json` which other `tsconfig.json` files in the directory structure reference. An example is probably more helpful: https://github.com/chooban/nx-testkit

I ended up adding a symlink of `tsconfig.json -> tsconfig.base.json` in the root to get ts-auto-guard to work. I'd completely forgotten about that! 

I wonder if this means I'm using it in an unexpected way, as I would run `ts-auto-guard libs/shared/interfaces/my-file.ts` from the root of the project, not from the library directory. 

Do you think that might be causing a conflict of interests between things?

**Comment by rhys-vdw** [comment]
> I wonder if this means I'm using it in an unexpected way, as I would run ts-auto-guard libs/shared/interfaces/my-file.ts from the root of the project, not from the library directory.

Well the idea is you should be able to run it from any directory, but can provide a path to the project via the (apparently undocumented) `project` option: https://github.com/rhys-vdw/ts-auto-guard/blob/e56198be832ee20f0beea4773fed358574ab8b28/src/cli.ts#L66-L70

**Comment by chooban** [comment]
I'm going to have a dig in the Project object to see if I can get the path to the config file from that. Without that it looks like it'd need to be passed through a long chain for a single use case.

**Comment by rhys-vdw** [comment]
> Without that it looks like it'd need to be passed through a long chain for a single use case.

Up to you, let's just open an issue otherwise.

**Comment by chooban** [comment]
Certainly from the point of view of a draft PR on my work project, merging this and filing an issue would be most advantageous for me! :D

**Pull request merged**
