### PR TITLE
Use unknown instead of any in type guards

### PR DESCRIPTION
**Pull request by sam-mfb**
PR to change the signature of generated types to use `unknown` rather than `any`.

### CODE REVIEW

**Review by download13 — APPROVED** [review]
Looks good to me.

Only note: Once we cast with `as Type` the type system no longer protects the generated code from "property access on undefined" runtime errors. A future improvement might be to cast each nested layer as `{ [k: string]?: unknown }` or something so that the type system will still catch any unchecked property access. Though that might balloon the size of the guards quite a bit unless someone knows a better way.

**Comment by sam-mfb** [comment]
I'm not sure how much type safety you are ever going to get inside a type guard.  This is of course true with the current implementations as well which has the type of the check object as `any`.  At least with an assertion you won't accidentally have typos in your property names (although, kind of a moot point with codegen).

I don't think you'll get runtime errors on nested types because it looks like the current codegen always tests to make sure that a nested interface is not null and is an object or function.  As long as that's true, the property on the object should always be undefined in the worst case, which will just cause the typeguard to return false.  Unless I'm misunderstanding what you were saying.

It would be nice if you could just use symantec javascript to narrow the types, but unfortunately this does not work:
```typescript
function isType(x:unknown): x is {prop:string} {
  return typeof x === "object" && // type narrowed from unknown to object | null
  x !== null && // type further narrowed to object
  ('prop' in x) && // TS does not realize that x.prop is valid :(
  typeof x.prop === "string"
}
```

**Comment by download13** [comment]
Aw that's a shame that typescript doesn't understand `in`. It would make sense for it to expand the type with a new property of type `unknown`. Maybe someday.

**Comment by rhys-vdw** [comment]
> I'm not sure how much type safety you are ever going to get inside a type guard
@sam-mfb 

Yeah, this is right. We theoretically don't need static checks (or types at all really) inside the generated code. That can be enforced with unit tests.

>  Though that might balloon the size of the guards quite a bit unless someone knows a better way.
This isn't really a concern, since they should be minified before going into production anyway. They're already pretty hectic.

**Comment by rhys-vdw** [comment]
Just published 3.1.0

**Comment by sam-mfb** [comment]
> Aw that's a shame that typescript doesn't understand `in`. It would make sense for it to expand the type with a new property of type `unknown`. Maybe someday.

Now it does (as of [4.9](https://devblogs.microsoft.com/typescript/announcing-typescript-4-9/#unlisted-property-narrowing-with-the-in-operator)).  I'm not sure a PR is worth it given the backwards compatibility issues, but it is here...

**Comment by rhys-vdw** [comment]
@sam-mfb feel free to open an issue, but I don't think it makes sense to make changes that aren't back compatible.

**Comment by sam-mfb** [comment]
> 

Totally agree.  I'm going to just leave it.

**Pull request merged**
