### PR TITLE
Update Packages

### PR DESCRIPTION
**Pull request by elliot-huffman**
Update everything and fix some security risks due to out-of-date dependencies.

### CODE REVIEW

**Comment by elliot-huffman** [comment]
@rhys-vdw, I would like to pull your attention to the uglify JS output changes, it no longer outputs the use strict directive (header) for the output. Is this, ok? or do we need to update our code to force it to emit the directive?

**Review by rhys-vdw — APPROVED** [review]

**Comment by rhys-vdw** [comment]
Hey Elliot, thanks for looking into that. I've sent you an invite to socket.

**Comment by rhys-vdw** [comment]
Also, I fixed one issue but I've still got an issue with the GitHub deploy action. Most likely just need to generate a new token... I should be able to find a moment to do it this week.

**Comment by elliot-huffman** [comment]
> Also, I fixed one issue but I've still got an issue with the GitHub deploy action. Most likely just need to generate a new token... I should be able to find a moment to do it this week.

If you need any help on that, let me know. I have a package of my own that I have an auto-publish workflow set up in GitHub Actions.

Here is a reference for my deployment pipeline for the package if you would like to compare and contrast yours:
https://github.com/Software-Hardware-Integration-Lab/ObjectID-Converter/blob/main/.github/workflows/NPM-Publish.yml

**Comment by rhys-vdw** [comment]
> If you need any help on that, let me know. I have a package of my own that I have an auto-publish workflow set up in GitHub Actions.

If you're interested I'm certainly open to any assistance/improvements, seems I published without a merge (see #258). However, I think the issue is just me needing to generate a new auth token for the workflow.

**Comment by elliot-huffman** [comment]
I'll take a peek :-)

**Pull request merged**
