### PR TITLE
Support string names in interfaces

### LINKED ISSUE #123: Support string names in interfaces
Interfaces defined with string names produce invalid guard files:
```ts
/**
 * Interface representing the payload of a JWT.
 * @see https://tools.ietf.org/html/rfc7519.
 * @see {isJwtPayload} ts-auto-guard:type-guard
 */
export interface JwtPayload extends Record<string, unknown> {
  'iss'?: string;
  'sub'?: string;
  'aud'?: string;
  'exp'?: number;
  'nbf'?: number;
  'iat'?: number;
  'jti'?: string;
}
```
```ts
export function isJwtPayload(obj: any, _argumentName?: string): obj is JwtPayload {
    return (
        (obj !== null &&
            typeof obj === "object" ||
            typeof obj === "function") &&
        (typeof obj.'iss' === "undefined" ||
            typeof obj.'iss' === "string") &&
                (typeof obj.'sub' === "undefined" ||
                    typeof obj.'sub' === "string") &&
                        (typeof obj.'aud' === "undefined" ||
                            typeof obj.'aud' === "string") &&
                                (typeof obj.'exp' === "undefined" ||
                                    typeof obj.'exp' === "number") &&
                                        (typeof obj.'nbf' === "undefined" ||
                                            typeof obj.'nbf' === "number") &&
                                                (typeof obj.'iat' === "undefined" ||
                                                    typeof obj.'iat' === "number") &&
                                                        (typeof obj.'jti' === "undefined" ||
                                                            typeof obj.'jti' === "string")
)
}
```
The code generator should use square brackets, either just for string names or all interface members in general.

### PR DESCRIPTION
**Pull request by chrisczach**
~~Removed resolution for #123~~

### CODE REVIEW

**Comment by rhys-vdw** [comment]
That's odd, CI doesn't seem to be running anymore. :-(

We should add in the test case you shared in the issue thread too.

**Comment by chrisczach** [comment]
> That's odd, CI doesn't seem to be running anymore. :-(
> 
> We should add in the test case you shared in the issue thread too.

Oh it looks like this doesn't fix #123, I was having another issue that i thought had the same cause. Where it was having issues with Interfaces with spaces which this PR does fix. I might take a look at what might be causing #123.

**Comment by rhys-vdw** [comment]
If it's no trouble, @chrisczach, that would be great. Please just add any test cases along with the changes to avoid regressions in future.

**Comment by chrisczach** [comment]
@rhys-vdw Found the cause of the bug for issue #123, also added the test case that were mentioned on that issue.

**Comment by rhys-vdw** [comment]
Hey @chrisczach, this is a fine fix, but I think the real fix is this one: #118 (which I mentioned in #124). This is because keys that contain _any_ invalid identifier character must be quoted, not just space.

I'm going to merge this now, thank you for the submission, and then open an issue to restore this more comprehensive handling for @0xorial. I do want to upstream this concern with ts-morph though... Did you try updating it to latest?

**Comment by chrisczach** [comment]
Yeah, I tried updating to the latest ts-morph and the issue was still there.

**Pull request merged**
