### PR TITLE
Make tests cross-platform

### LINKED ISSUE #67: Windows support
package.json contains some linux-specific code:

- chmod in 'build' command
- bunch of stuff in 'test' command

I am wondering if it could be improved somehow. I made some [workarounds](https://github.com/0xorial/ts-auto-guard/commit/3eda7f171e1650644cea83e0ab17bd1a944b9640#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L7), but I am not very happy about them...

### PR DESCRIPTION
**Pull request by 0xorial**
Should fix #67 . I am not 100% about chmod removal - it seems redundant and I quickly tested on ubuntu and it seemed to work, but still dunno what was the story behind.

### CODE REVIEW

**Comment by rhys-vdw** [comment]
@0xorial I added that to make sure that the cli was executable. That said, I remember thinking it seemed odd to require it. When you say you tested on ubuntu, you mean you build and manually ran the cli, or just ran the tests?

**Comment by rhys-vdw** [comment]
Looks good though, happy to merge if the CLI is still working.

**Comment by rhys-vdw** [comment]
Actually I'm just going to merge now cos I'm in windows too.

**Comment by 0xorial** [comment]
@rhys-vdw my approach was to add npm dependency with link to a specific commit (which in my understanding should build the package), do `npm install` and then run ts-auto-guard from another npm script. I only have a console access to my ubuntu machine though so I expect around 25% chance of making some error...

**Comment by rhys-vdw** [comment]
@0xorial oh well... we'll see. Apparently the current release is broken anyway so it can't get much worse. ;-)

**Pull request merged**
