### PR TITLE
Possible tests fix for windows

### PR DESCRIPTION
**Pull request by 0xorial**

### CODE REVIEW

**Comment by 0xorial** [comment]
Do we need absolute paths there or we can leave it like that?

**Comment by rhys-vdw** [comment]
Hahah nice. Yeah this works on windows:

```
passed: 259  failed: 0  of 259 tests  (13.2s)

All of 259 tests passed!
```

**Comment by rhys-vdw** [comment]
> Do we need absolute paths there or we can leave it like that?

Don't see why we would. I guess ideally we'd have a windows test suite but it seems pretty niche since it's not affecting the actual library itself.

**Comment by rhys-vdw** [comment]
Closes #145

**Pull request merged**
