### PR TITLE
Added --no-superfluous-properties cli option

### PR DESCRIPTION
**Pull request by ViSaturn**
Added a cli option that disallows objects from having extra properties that are not in the interface / type that they are expected to match.

This uses dsherret's code-block-writer for the checks.

### CODE REVIEW

**Comment by ViSaturn** [comment]
Just realized this still needs support for Enums, which I think I can do fairly easily in a moment.

On another note, I didn't write tests for this because I dislike the way that the tests are done, specifically I don't like directly checking the code produced, it would be nice if ts-auto-guard outputted an array specifically for tests & debugging that contains a log of the type checks and type guard functions it made, and I think it would be more reliable to test that instead. I'm not sure how easy this is tho, I'm thinking the eq / ne / typeOf functions can be created under a factory function that can take a logs or test boolean parameter that'll make eq / ne /typeOf generate logs.

Something similar to this:
```typescript
function makeHelperFunctions(callback: (log: string) => any, logs: boolean = false) {
  if (logs) {
    return {
      eq(a: string, b: string) {
        callback("A STRICT_EQUALS B")
        return `${a} === ${b}`
      }
    }
  } else {
    return {
      eq = (a: string, b: string) => return `${a} === ${b}`
    }
  }
}

const { eq } = makeHelperFunctions(someRandomFunction, true)

```

And in the end the tests will look something like this
```typescript
it("should generate an awesome type guard", function () {
  testProcessProject(`
interface MyInterface {
  propA: "hello world!"
}
`, [
'MAKE_TYPE_GUARD_FUNCTION_FOR_MyInterface',

'TYPEOF MyInterface[propA] STRICT_EQUALS \'string\'',
'MyInterface[propA] STRICT_EQUALS \'hello world!\'',

'END_TYPE_GUARD_FUNCTION_FOR_MyInterface'
]
})
```
I feel like the above is a bit better rather than directly comparing code as the generated code could change for many reasons, but not affect tests or cause problems, and I can open another PR that will allow these kinds of tests after I get thoughts on this.

Also, although I have not written tests *yet* I can confirm from personal usage that:
- If the --no-superfluous-properties flag is not there these won't be generated
- If the --debug flag is not there, debug information will not be generated
- And that it works for interfaces atleast, but types SHOULD work just fine too

**Comment by rhys-vdw** [comment]
Thank you for your contribution @ViSaturn!

Hm, this is interesting, but that's how how types work in TypeScript. Interfaces are satisfied when a type has a set of properties. AFAIK there is no way to say "this type has exactly these properties and nothing more".

I'm not sure if this is an appropriate thing to add a type guard generator, as it's not creating a true type guard. (Also, even if it were, I don't think it makes sense to add as a global option, as opposed to a per-guard option.)

I will leave the PR open in case other collaborators have a differing opinion.

**Comment by ViSaturn** [comment]
> Hm, this is interesting, but that's how how types work in TypeScript. Interfaces are satisfied when a type has a set of properties. AFAIK there is no way to say "this type has exactly these properties and nothing more".

That is true, I added it because I'm coming from `typescript-is` which does not allow superfluous properties and I got used to that to check if there were any additions to foreign json, and typescript-is seems to no longer be maintained, and is also incompatible with TypeScript 4.8 so I thought it would be nice for people who would be migrating to ts-auto-guard.

> I'm not sure if this is an appropriate thing to add a type guard generator, as it's not creating a true type guard. (Also, even if it were.

I understand what you mean when you say it's not a 'true type guard', it does more than what a regular TypeScript interface / type / enum checks for you. Which means there would be scenarios where the type guard would fail but TypeScript would see your object as being compatible with the interface / type / enum. And I can see why you would not merge this for that reason.

> I don't think it makes sense to add as a global option, as opposed to a per-guard option.)

#204 could solve this.

> I will leave the PR open in case other collaborators have a differing opinion.

**Comment by ViSaturn** [comment]
I did some searching and noticed that this was a thing:
```typescript
type NoExtra<Type> = {
  [Property in keyof Type]: any;
};

type a = NoExtra<{
  b: "hello";
  c: "hi";
}>;

const myA: a = {
  b: "hello",
  c: "hi",
  d: "whoops",
};
```

tsc gives an error: TS2322 for property d, because it is not in the type

Now I feel like kind of dumb for not searching for something like this before I made this pull request, but I think I can adapt this pull request for this, would def take a bit of work tho.

**Comment by ViSaturn** [comment]
```typescript
type NoExtra<Type> = {
  [Property in keyof Type]: any;
};

type Greetings = NoExtra<{
  a: "hello";
  b: "hi";
}>;
```
The main issue stopping me from starting on this now is that I'm not sure how to solve is what if `NoExtra` was imported from somewhere? How would I know it's a mapped type? I'm gonna check if ts-morph has something to help with this.

**Comment by ViSaturn** [comment]
Actually I Just realized..
```typescript
type Only<Type> = {
  [Property in keyof Type]: Type[Property]
}

type Greetings = Only<{
  a: "hello"
}>

const myGreeting = {
  a: "hello",
  b: "hi", // -> TS2322: b does not exist in type blablabla
}
```
If you had something like this, it's all fine but the Only type literally does nothing, if I were to omit the Only type and do this:
```typescript
type Greetings = {
  a: "hello"
}

const myGreeting = {
  a: "hello"
  b: "hi" // -> TS233: b does not exist in type blablabla
}
```
It literally gives off the same error, but in my tests interfaces are completely fine and extra properties are okay in interfaces. So now I'm just kind of confused but I guess we could keep the flag but only apply it to types and not interfaces? I haven't tested Enum's yet....

**Comment by rhys-vdw** [comment]
This is true at declaration time, but your extra properties would still be accepted when passing the object into a method that accepts `Greetings`.

`Only` is a new concept for me. It's quite possible that we should be supporting the superfluous type check there!

Do you know how it works? I'm wondering if it adds something like `[key: any]: never` into the interface.

**Comment by ViSaturn** [comment]
> Do you know how it works? I'm wondering if it adds something like `[key: any]: never` into the interface.

This is what I thought when I first tried this but it seems I was incorrect

```typescript
type Only<T> = {
    [Property in keyof T]: T[Property]
}

type OTGreeting = Only<{
    a: "Hello"
}>

function acceptOTGreeting(greeting: OTGreeting) {
    console.log(greeting)
}

const untypedGreeting = {
    a: "Hello" as "Hello",
    b: "Hi",
    c: "Good day"
}

acceptOTGreeting(untypedGreeting) // no error
acceptOTGreeting({
    a: "Hello" as "Hello"
})
```
TypeScript wont error when passing `untypedGreeting` to `acceptOTGreeting` even though it has 2 extra properties (b and c)

The only way it seems to let a function accept an Exact type is by doing this:
```typescript
type TGreeting = {
    a: "Hello"
}

type Exact<A, B> = A extends B
    ? B extends A
    ? A
    : never
    : never

function acceptOTGreeting<T>(greeting: Exact<T, TGreeting>) {
    console.log(greeting)
}

const untypedGreeting = {
    a: "Hello" as "Hello",
    b: "Hi",
    c: "wsasup"
}

acceptOTGreeting(untypedGreeting) // ERROR!
acceptOTGreeting({
    a: "Hello" as "Hello"
})
```
In this example it'll give an error for the untypedGreeting, but this is for functions, so it seems there is no way to specify that all implementations of a type be Exact, from the declaration of the type itself, Exact types can only be enforced if you explicitly use the Exact type shown above to compare two types in a function or something, but that does mean you could do something like this:
```typescript
type TGreeting = {
    a: "Hello"
}

type Exact<A, B> = A extends B
    ? B extends A
    ? A
    : never
    : never

const ConfirmTGreeting = <T>(param: Exact<T, TGreeting>): TGreeting => param

const myGreeting = ConfirmTGreeting({
    a: "Hello",
})

const myExtraPropGreeting = ConfirmTGreeting({
    a: "Hello",
    b: "Hi"// -> nope
})
```
This is okay but it still relies on functions to check the type.

Anyways sorry for that confusion about that.
My fork works fine for me right now but if you're still interested in merging this I would be fine with writing tests for the flag.

**Comment by download13** [comment]
I found [this issue on the typescript repo](https://github.com/Microsoft/TypeScript/issues/12936) which seems to indicate that exact types (a la `type Exact<T> = ...`) are not supported at the moment. Without that, we'd be trying to generate a guard clause for a generic type (like `Exact<T, TGreeting>`), which as far as I know is not possible.

If typescript can't express exact types in concrete terms, making guards for them wouldn't mean much.

It might make more sense to make a converter function that takes in a product type, and returns the same type, but with all extraneous properties stripped out.

For example, for the following type:
```ts
type Cat = { type: 'cat', name: string }
```
we might generate:
```ts
function toExactCat(v: Cat): Cat{
  return { type: 'cat', name: v.name }
}
```
and a function that requires exact data could use it as a sort of input converter:
```ts
function send(cat: Cat): void {
  cat = toExactCat(cat)
  ...
}
```

Typescript won't protect you from forgetting to add the converter, but generating them is something a script could do.

That functionality feels like something a different generator library should do though. This is `ts-auto-guard`, with guards being well-defined within typescript. Since `Exact` types are not well-defined in typescript it might be better to make another library to generate exact converters. It would also be substantially simpler than this library since it would only need to operate on the own properties of product types.

**Comment by rhys-vdw** [comment]
Thanks @download13. I think this is an interesting feature, but I do want to be strict about the goals of this library. Especially while it's not quite perfect at performing those. I really do appreciate your contributions @ViSaturn, and hope the push back on your issues and PRs won't discourage you from contributing other improvements.

I think I'll close this for now. If `Exact<T>` becomes supported by TS we can look at implementing it.

**Comment by download13** [comment]
@ViSaturn Yeah I feel bad, like the last few things you've submitted I was kind of shooting down, but I hope you keep contributing to open-source projects!

I'm glad to hear that your fork is working for you. We can reference it if typescript ever does get proper exact types.

**Pull request closed without merging**
